import {
  // Existing icons
  BookOpen,
  FileText,
  PenTool,
  Lightbulb,
  Target,
  Heart,
  Star,
  Coffee,
  Music,
  Camera,
  Map as MapIcon,
  Bookmark,
  Calendar,
  Clock,
  Globe,
  Home,
  Briefcase,
  ShoppingCart,
  Gamepad2,
  Rocket,

  // Additional useful icons for notes and background
  Brain,
  Book,
  Notebook,
  PenSquare,
  Highlighter,
  Hash,
  Quote,
  Type,
  AlignLeft,
  AlignCenter,
  List,
  CheckSquare,
  Circle,
  Square,
  Triangle,
  Hexagon,

  // Nature & Objects
  Sun,
  Moon,
  CloudRain,
  Umbrella,
  Trees,
  Flower,
  Leaf,
  Mountain,
  Waves,

  // Technology
  Smartphone,
  Laptop,
  Monitor,
  Wifi,
  Database,
  Server,
  Code,
  Terminal,
  Github,

  // Communication
  MessageCircle,
  Mail,
  Phone,
  Video,
  Mic,
  Bell,
  Megaphone,

  // Transportation
  Car,
  Plane,
  Train,
  Bike,
  Bus,
  Ship,

  // Food & Drink
  UtensilsCrossed,
  Wine,
  Pizza,
  Apple,

  // Activities
  Dumbbell,
  Gamepad,
  Guitar,
  Headphones,
  Palette,
  Brush,
  Scissors,
  Wrench,

  // Business & Finance
  TrendingUp,
  DollarSign,
  CreditCard,
  PiggyBank,
  Building,
  Store,

  // Health & Medical
  Stethoscope,
  Pill,
  Activity,
  Zap,

  // Education
  GraduationCap,
  School,
  Library,
  Award,
  Trophy,

  // Emotions & People
  Smile,
  Frown,
  Meh,
  ThumbsUp,
  ThumbsDown,
  Users,
  User,
  UserCheck,

  // Abstract & Symbols
  Sparkles,
  Flame,
  Snowflake,
  Droplet,
  Eye,
  Lock,
  Key,
  Shield,

  // Arrows & Navigation
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ChevronUp,
  ChevronDown,
  ChevronLeft,
  ChevronRight,

  // Media & Entertainment
  Play,
  Pause,
  Square as SquareIcon,
  Volume2,
  VolumeX,
  Image,
  Film,

  // Common UI
  Plus,
  Minus,
  X,
  Check,
  Search,
  Filter,
  Settings,
  MoreHorizontal,
  MoreVertical,
  Edit,
  Trash2,
  Download,
  Upload,
  Share2,
  Copy,
  type LucideIcon,
} from 'lucide-react-native';

// Registry of all available icons
export const ICON_REGISTRY = {
  // Writing & Notes
  'book-open': BookOpen,
  'file-text': FileText,
  'pen-tool': PenTool,
  lightbulb: Lightbulb,
  brain: Brain,
  book: Book,
  notebook: Notebook,
  'pen-square': PenSquare,
  highlighter: Highlighter,
  hash: Hash,
  quote: Quote,
  type: Type,
  'align-left': AlignLeft,
  'align-center': AlignCenter,
  list: List,
  'check-square': CheckSquare,

  // Shapes
  circle: Circle,
  square: Square,
  triangle: Triangle,
  hexagon: Hexagon,

  // Common Items
  target: Target,
  heart: Heart,
  star: Star,
  coffee: Coffee,
  music: Music,
  camera: Camera,
  map: MapIcon,
  bookmark: Bookmark,
  calendar: Calendar,
  clock: Clock,
  globe: Globe,
  home: Home,
  briefcase: Briefcase,
  'shopping-cart': ShoppingCart,
  gamepad: Gamepad2,
  rocket: Rocket,

  // Nature
  sun: Sun,
  moon: Moon,
  'cloud-rain': CloudRain,
  umbrella: Umbrella,
  tree: Trees,
  flower: Flower,
  leaf: Leaf,
  mountain: Mountain,
  waves: Waves,

  // Technology
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  wifi: Wifi,
  database: Database,
  server: Server,
  code: Code,
  terminal: Terminal,
  github: Github,

  // Communication
  'message-circle': MessageCircle,
  mail: Mail,
  phone: Phone,
  video: Video,
  mic: Mic,
  bell: Bell,
  megaphone: Megaphone,

  // Transportation
  car: Car,
  plane: Plane,
  train: Train,
  bike: Bike,
  bus: Bus,
  ship: Ship,

  // Food & Drink
  'utensils-crossed': UtensilsCrossed,
  wine: Wine,
  pizza: Pizza,
  apple: Apple,

  // Activities
  dumbbell: Dumbbell,
  'gamepad-alt': Gamepad,
  guitar: Guitar,
  headphones: Headphones,
  palette: Palette,
  brush: Brush,
  scissors: Scissors,
  wrench: Wrench,

  // Business & Finance
  'trending-up': TrendingUp,
  'dollar-sign': DollarSign,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  building: Building,
  store: Store,

  // Health & Medical
  stethoscope: Stethoscope,
  pill: Pill,
  activity: Activity,
  zap: Zap,

  // Education
  'graduation-cap': GraduationCap,
  school: School,
  library: Library,
  award: Award,
  trophy: Trophy,

  // Emotions & People
  smile: Smile,
  frown: Frown,
  meh: Meh,
  'thumbs-up': ThumbsUp,
  'thumbs-down': ThumbsDown,
  users: Users,
  user: User,
  'user-check': UserCheck,

  // Abstract & Symbols
  sparkles: Sparkles,
  flame: Flame,
  snowflake: Snowflake,
  droplet: Droplet,
  eye: Eye,
  lock: Lock,
  key: Key,
  shield: Shield,

  // Arrows & Navigation
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,

  // Media & Entertainment
  play: Play,
  pause: Pause,
  'square-icon': SquareIcon,
  volume: Volume2,
  'volume-x': VolumeX,
  image: Image,
  film: Film,

  // Common UI
  plus: Plus,
  minus: Minus,
  x: X,
  check: Check,
  search: Search,
  filter: Filter,
  settings: Settings,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  edit: Edit,
  trash: Trash2,
  download: Download,
  upload: Upload,
  share: Share2,
  copy: Copy,
} as const;

export type IconName = keyof typeof ICON_REGISTRY;
export type IconComponent = LucideIcon;

// Helper function to get icon component by name
export function getIconComponent(name: IconName): IconComponent | null {
  return ICON_REGISTRY[name] || null;
}

// Get all available icon names
export function getAvailableIconNames(): IconName[] {
  return Object.keys(ICON_REGISTRY) as IconName[];
}

// Icon categories for better organization
export const ICON_CATEGORIES = {
  writing: [
    'book-open',
    'file-text',
    'pen-tool',
    'lightbulb',
    'brain',
    'book',
    'notebook',
    'pen-square',
    'highlighter',
    'hash',
    'quote',
    'type',
  ],
  shapes: ['circle', 'square', 'triangle', 'hexagon', 'star'],
  nature: [
    'sun',
    'moon',
    'cloud-rain',
    'umbrella',
    'tree',
    'flower',
    'leaf',
    'mountain',
    'waves',
  ],
  technology: [
    'smartphone',
    'laptop',
    'monitor',
    'wifi',
    'database',
    'server',
    'code',
    'terminal',
    'github',
  ],
  communication: [
    'message-circle',
    'mail',
    'phone',
    'video',
    'mic',
    'bell',
    'megaphone',
  ],
  transportation: ['car', 'plane', 'train', 'bike', 'bus', 'ship'],
  food: ['utensils-crossed', 'wine', 'pizza', 'apple', 'coffee'],
  activities: [
    'dumbbell',
    'gamepad-alt',
    'guitar',
    'headphones',
    'palette',
    'brush',
    'scissors',
    'wrench',
    'music',
    'camera',
  ],
  business: [
    'trending-up',
    'dollar-sign',
    'credit-card',
    'piggy-bank',
    'building',
    'store',
    'briefcase',
  ],
  health: ['stethoscope', 'pill', 'activity', 'zap'],
  education: ['graduation-cap', 'school', 'library', 'award', 'trophy'],
  emotions: ['smile', 'frown', 'meh', 'thumbs-up', 'thumbs-down', 'heart'],
  people: ['users', 'user', 'user-check'],
  symbols: [
    'sparkles',
    'flame',
    'snowflake',
    'droplet',
    'eye',
    'lock',
    'key',
    'shield',
    'target',
  ],
  navigation: [
    'arrow-up',
    'arrow-down',
    'arrow-left',
    'arrow-right',
    'chevron-up',
    'chevron-down',
    'chevron-left',
    'chevron-right',
  ],
  media: [
    'play',
    'pause',
    'square-icon',
    'volume',
    'volume-x',
    'image',
    'film',
  ],
  common: [
    'plus',
    'minus',
    'x',
    'check',
    'search',
    'filter',
    'settings',
    'more-horizontal',
    'more-vertical',
    'edit',
    'trash',
    'download',
    'upload',
    'share',
    'copy',
    'bookmark',
    'calendar',
    'clock',
    'globe',
    'home',
  ],
} as const;

export const NOTE_ICONS = {
  writing: [
    'book-open',
    'file-text',
    'pen-tool',
    'lightbulb',
    'brain',
    'book',
    'notebook',
    'pen-square',
    'highlighter',
    'quote',
  ],
  shapes: ['circle', 'square', 'triangle', 'hexagon', 'star'],
  nature: [
    'sun',
    'moon',
    'cloud-rain',
    'tree',
    'flower',
    'leaf',
    'mountain',
    'waves',
  ],
  technology: ['smartphone', 'laptop', 'monitor', 'code', 'terminal', 'wifi'],
  activities: [
    'music',
    'camera',
    'gamepad-alt',
    'guitar',
    'headphones',
    'palette',
    'brush',
    'dumbbell',
  ],
  common: [
    'target',
    'heart',
    'coffee',
    'bookmark',
    'calendar',
    'clock',
    'globe',
    'home',
    'briefcase',
    'shopping-cart',
    'rocket',
  ],
  food: ['utensils-crossed', 'wine', 'pizza', 'apple'],
  transportation: ['car', 'plane', 'train', 'bike', 'bus', 'ship'],
  business: [
    'trending-up',
    'dollar-sign',
    'building',
    'store',
    'award',
    'trophy',
  ],
  emotions: ['smile', 'frown', 'meh', 'thumbs-up', 'thumbs-down'],
  symbols: [
    'sparkles',
    'flame',
    'snowflake',
    'droplet',
    'eye',
    'lock',
    'key',
    'shield',
  ],
} as const;

export const ICON_CATEGORIES_PT = {
  writing: 'Escrita',
  shapes: 'Formas',
  nature: 'Natureza',
  technology: 'Tecnologia',
  activities: 'Atividades',
  common: 'Comum',
  food: 'Comida',
  transportation: 'Transporte',
  business: 'Negócios',
  emotions: 'Emoções',
  symbols: 'Símbolos',
} as const;

export function getIconCategoryLabel(category: IconCategory): string {
  return ICON_CATEGORIES_PT[category];
}

export type IconCategory = keyof typeof ICON_CATEGORIES;
